export const ROUTE_LOGIN = '/login'
export const ROUTE_SECURE = '/secure'
export const ROUTE_UPDATE_PASSWORD = ROUTE_SECURE + '/update-password'
export const ROUTE_MAIN = ROUTE_SECURE + '/main'
export const ROUTE_MAINTAIN_MEMBERS = ROUTE_SECURE + '/maintain-members'